// Pure report + export formatting.
//
// The point of this module: an agency or in-house marketer needs to hand someone
// else proof that a tag is broken. A screenshot of a popup isn't evidence; a
// pasteable verdict is. Kept pure (timestamps are passed in, never read) so it can
// be unit-tested without a browser.

import { deriveBaseStatus, deriveWarnings, getPartnerIds } from './state.js';

const STATUS_LABEL = {
  firing: 'FIRING — the tag loaded and reached LinkedIn',
  present: 'PRESENT, NOT FIRING — the tag is on the page but nothing fired',
  blocked: 'BLOCKED — requests were blocked in this browser (ad or consent blocker)',
  'not-found': 'NOT FOUND — no LinkedIn Insight Tag detected'
};

function stamp(ts) {
  if (!ts) return '';
  try {
    return new Date(ts).toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC');
  } catch {
    return '';
  }
}

/**
 * A client-ready plain-text verdict.
 *
 * @param {object} state
 * @param {{host?: string, now?: number}} opts
 * @returns {string}
 */
export function formatReport(state, { host = '', now = 0 } = {}) {
  const status = deriveBaseStatus(state);
  const pids = getPartnerIds(state);
  const warnings = deriveWarnings(state);
  const conversions = [...(state.conversions || [])].sort((a, b) => (b.ts || 0) - (a.ts || 0));

  const lines = [];
  lines.push('LinkedIn Insight Tag — check report');
  lines.push('='.repeat(40));
  if (host) lines.push(`Page:    ${host}`);
  if (now) lines.push(`Checked: ${stamp(now)}`);
  lines.push(`Status:  ${STATUS_LABEL[status] || status}`);
  lines.push('');

  lines.push(`Partner IDs (${pids.length}): ${pids.length ? pids.join(', ') : 'none detected'}`);
  lines.push('');

  lines.push(`Event conversions (${conversions.length}):`);
  if (!conversions.length) {
    lines.push('  none captured');
  } else {
    for (const c of conversions) {
      const mark = c.fired ? '[fired]' : c.errorKind === 'blocked' ? '[blocked]' : '[not fired]';
      const via = [c.viaLintrk ? 'lintrk' : null, c.viaNetwork ? 'pixel' : null]
        .filter(Boolean)
        .join(' + ');
      lines.push(`  ${mark} #${c.conversionId}${via ? `  (${via})` : ''}`);
    }
  }

  if (warnings.length) {
    lines.push('');
    lines.push('Notes:');
    for (const w of warnings) {
      lines.push(`  ${w.level === 'info' ? '-' : '!'} ${w.message}`);
    }
  }

  // Other vendors seen alongside — context, never part of the LinkedIn verdict.
  const others = new Set(
    (state.timeline || [])
      .filter((e) => e.kind === 'request' && e.tier === 'observed')
      .map((e) => e.providerName)
  );
  if (others.size) {
    lines.push('');
    lines.push(`Also seen on this page: ${[...others].join(', ')}`);
  }

  lines.push('');
  lines.push('Generated by Insight Tag Checker for LinkedIn (all analysis local).');
  return lines.join('\n');
}

const CSV_COLUMNS = [
  'timestamp',
  'page',
  'provider',
  'type',
  'label',
  'account',
  'conversion_id',
  'result',
  'http_status',
  'error',
  'url'
];

function csvCell(value) {
  const s = String(value ?? '');
  // Quote when the value contains a delimiter, quote or newline; double inner quotes.
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function resultOf(entry) {
  if (entry.kind === 'lintrk') return 'intent';
  if (entry.errorKind === 'aborted') return 'cancelled by navigation';
  if (entry.errorKind) return entry.errorKind;
  return entry.phase === 'completed' ? 'fired' : 'pending';
}

/**
 * The raw decoded log as CSV, for pasting into a sheet or attaching to a ticket.
 * @param {Array<object>} timeline
 */
export function timelineToCsv(timeline = []) {
  const rows = [CSV_COLUMNS.join(',')];

  for (const e of timeline) {
    if (e.kind === 'page') {
      rows.push([stamp(e.ts), e.seq, '', 'page load', e.url, '', '', '', '', '', e.url].map(csvCell).join(','));
      continue;
    }
    rows.push(
      [
        stamp(e.ts),
        e.seq,
        e.providerName || '',
        e.isConversion ? 'conversion' : 'event',
        e.label || '',
        e.account || '',
        e.conversionId || '',
        resultOf(e),
        e.statusCode ?? '',
        e.errorKind || '',
        e.url || ''
      ]
        .map(csvCell)
        .join(',')
    );
  }

  return rows.join('\n');
}
